<?php
/**
 * @file
 * Code for the Bean Cta Settings feature.
 */

include_once 'idi_bean_settings.features.inc';
include_once 'idi_bean_settings.features.field_base.inc';
include_once 'idi_bean_settings.features.field_instance.inc';

function  idi_bean_settings_install(){
    idi_bean_settings_load_fields();
}



function idi_bean_settings_load_fields(){
    foreach(idi_bean_settings_field_default_field_bases() as $field_base){
        field_create_field($field_base);
    }
    foreach(idi_bean_settings_field_default_field_instances() as $field_instance){
        field_create_instance($field_instance);
    }

}
